import type { ThrowableDefinition, WeaponDefinition } from "./types.ts";

// Authored starting values, to be tuned through playtesting. They are not
// recovered Mini Militia balance numbers.
export const WEAPONS: Record<string, WeaponDefinition> = {
  "mini-eagle": {
    id: "mini-eagle",
    name: "Mini Eagle",
    category: "sidearm",
    damage: 24,
    pellets: 1,
    spread: 0.02,
    cooldownMs: 260,
    auto: false,
    mag: 12,
    reserve: 48,
    reloadMs: 1100,
    range: 760,
    zoom: 1,
    oneHanded: true,
    heavy: false,
    color: 0xd9d4c7,
  },
  uzi: {
    id: "uzi",
    name: "Uzi",
    category: "smg",
    damage: 9,
    pellets: 1,
    spread: 0.11,
    cooldownMs: 70,
    auto: true,
    mag: 30,
    reserve: 120,
    reloadMs: 1300,
    range: 560,
    zoom: 1,
    oneHanded: true,
    heavy: false,
    color: 0x6f7a80,
  },
  ak47: {
    id: "ak47",
    name: "AK-47",
    category: "rifle",
    damage: 17,
    pellets: 1,
    spread: 0.045,
    cooldownMs: 115,
    auto: true,
    mag: 30,
    reserve: 90,
    reloadMs: 1700,
    range: 980,
    zoom: 1.25,
    oneHanded: false,
    heavy: false,
    color: 0x8a5a2b,
  },
  spas12: {
    id: "spas12",
    name: "SPAS-12",
    category: "shotgun",
    damage: 11,
    pellets: 7,
    spread: 0.2,
    cooldownMs: 720,
    auto: false,
    mag: 6,
    reserve: 24,
    reloadMs: 2000,
    range: 400,
    zoom: 1,
    oneHanded: false,
    heavy: false,
    color: 0x3b3f44,
  },
};

export const THROWABLES: Record<string, ThrowableDefinition> = {
  frag: {
    id: "frag",
    name: "Fragmentation grenade",
    fuseMs: 2200,
    radius: 135,
    maxDamage: 110,
    minDamage: 15,
    throwSpeed: 640,
    bounce: 0.42,
  },
};

export const IMPLEMENTED_WEAPONS = Object.keys(WEAPONS);
export const IMPLEMENTED_THROWABLES = Object.keys(THROWABLES);
